#!/usr/bin/env bash

basedir="$HOME/.todo$(pwd)"

basedir_exists() {
  return $([[ -d "${basedir}" ]])
}

[ ! -z "$1" ] || exit 0

case "${1}" in
  count)
    basedir_exists || { echo 0; exit 0; }
    find "${basedir}" -maxdepth 1 -type f | wc -l
    ;;

  *)
    mkdir -p "${basedir}"
    echo "$@" > "${basedir}/`date +%s`"
    ;;
esac
