#!/usr/bin/env bash

TODO_DATE="${TODO_DATE:-%F %T}"
TODO_ROOT="${TODO_ROOT:-$HOME/.todo}"

basedir="${TODO_ROOT}$(pwd)"

basedir_exists() {
  return $([[ -d "${basedir}" ]])
}

[ ! -z "$1" ] || exit 0

case "${1}${2}" in
  clear)
    basedir_exists || { exit 0; }

    find "${basedir}" -maxdepth 1 -type f -exec rm {} \;
    ;;

  count)
    basedir_exists || { echo 0; exit 0; }
    find "${basedir}" -maxdepth 1 -type f | wc -l
    ;;

  list)
    basedir_exists || { exit 0; }

    todos=( $(find "${basedir}" -maxdepth 1 -type f | sort -n) )

    todo_num=${#todos[@]}
    pad_len="${#todo_num}"
    pad_str="            "

    for i in "${!todos[@]}"; do
        n=$((1 + $i))

        echo -n "${pad_str:0:$(($pad_len - ${#n}))}${n} | "
        echo -n "$(date -d @$(basename ${todos[$i]}) +"${TODO_DATE}"): "
        cat "${todos[$i]}"
    done
    ;;

  *)
    mkdir -p "${basedir}"
    echo "$@" > "${basedir}/`date +%s`"
    ;;
esac
