name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - test
  workflow_dispatch:

jobs:
  quality_actions:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - run: yamllint .
        working-directory: .github

  quality_shell:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: completions test

  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: mig4/setup-bats@v1

      - name: test
        run: bats --tap ./test/
