name: Code Quality

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ludeeus/action-shellcheck@master
      with:
        ignore: completions test
