name: Code Quality

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: completions test
