name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - test
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: mig4/setup-bats@v1

      - name: test
        run: bats --tap ./test/
