name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: mig4/setup-bats@v1

    - name: test
      run: bats --tap ./test/
