name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: mig4/setup-bats@v1

      - name: test
        run: bats --tap ./test/
